[tools]
bun = "1.2.17"

[env]
_.file = ".env.json"

[tasks.typecheck]
run = "bun --bun tsgo --noEmit --pretty -p ./tsconfig.json"
description = "Typecheck the project using tsgo"
alias = "tc"

[tasks.build]
run = "bun run build.ts"
description = "Build the plugin"
alias = "b"
depends_post = "copy"

[tasks.copy]
run = [
  "eza --color=always --group-directories-first --icons -l dist",
  "cp dist/main.js {{env.OUTPUT_DIR}}/main.js",
  "cp dist/main.js.map {{env.OUTPUT_DIR}}/main.js.map",
]
description = "Copy output files to plugin dir"